name: Build Project

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    name: Maven Setup
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'
      - name: Maven Setup
        run: mvn -B package

  build:
    runs-on: ubuntu-latest
    needs: setup
    timeout-minutes: 3

    strategy:
      matrix:
        java-version: [8, 11, 16, 17, 18]

    name: Build Java ${{ matrix.java-version }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}
          cache: 'maven'
      - name: Build with Maven
        run: |
          mvn clean install
  deploy:
    runs-on: ubuntu-latest
    needs: setup
    name: Deploy JavaDocs
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 16
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '16'
          cache: 'maven'

      - name: Build JavaDocs
        run: |
          mvn package -pl "api"
      - name: Deploy JavaDoc
        run: bash javadoc.sh