name: Build Project
on: push
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    
    - name: Setup & Run BuildTools
      run: |
        wget -O BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
        java -jar BuildTools.jar --rev 1.18.2 --remapped
    - name: Build with Maven
      run: |
        mvn package clean
        mvn install
    - name: Generate JavaDoc
      run: |
        mvn install
        cd target/apidocs
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: myhsoting.com
        username: user@tutsplanet.com
        password: ${{ secrets.PROD_FTP_PWD }}'
        server-dir: htdocs/novaconomy/