name: Build Project
on:
  push:     
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:
  
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Setup Dependencies
      run: |
        wget -O BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
        java -jar BuildTools.jar --rev 1.18.2 --remapped
    - name: Build Project
      run: |
        mvn package clean
        mvn install
    - name: Build JavaDoc
      run: |
        mkdir docs
        cp -Rfv target/apidocs/* docs/
        cd docs
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add ./
        git commit -m "Update javadoc pages for latest release" -a
    - name: Push JavaDoc Changes
      uses: ad-m/github-push-action@master
      with:
        branch: main
        directory: docs
        github_token: ${{ secrets.ACTION_KEY }}